# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Home
email: noah.just@geo.uni-marburg.de
description: >- # this means to ignore newlines until "baseurl:"
  PhotoDB is a flexible image data management and annotation tool, that utilizes a machine- and human-readable metadata sidecar YAML file approach. PhotoDB is meant to be used as the backbone of your personal image processing workflow. Interaction with image metadata is possible at any point during a worklfow using any aribtrary programming language with YAML capabilities, allowig, e.g., for the integration of cusomized AI models.
baseurl: "/photodb_documentation" # the subpath of your site, e.g. /blog
url: "https://envima.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#- twitter_username: jekyllrb
github_username:  justNoah1699
repository: envima/photodb_documentation

# Build settings
# theme: minima
remote_theme: "mmistakes/minimal-mistakes-jekyll@v4.24.0"
minimal_mistakes_skin: "air" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist

# conversion
markdown: kramdown

include:
  - _pages

collections_dir: collections

collections:
  deployment:
    output: true
    permalink: /:collection/:title.html
  configuration:
    output: true
    permalink: /:collection/:title.html
  operating:
    output: true
    permalink: /:collection/:title.html
  usage:
    output: true
    permalink: /:collection/:title.html
  maintenance:
    output: true
    permalink: /:collection/:title.html
  
# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: page
    values:
      layout: single
  # deployment
  - scope:
      path: ""
      type: deployment
    values:
      layout: single
      category: deployment
      sidebar:
        nav: "deployment"
  # configuration
  - scope:
      path: ""
      type: configuration
    values:
      layout: single
      category: configuration
      sidebar:
        nav: "configuration"
  # operating
  - scope:
      path: ""
      type: operating
    values:
      layout: single
      category: operating
      sidebar:
        nav: "operating"
  # usage
  - scope:
      path: ""
      type: usage
    values:
      layout: single
      category: usage
      sidebar:
        nav: "usage"
  # maintenance
  - scope:
      path: ""
      type: maintenance
    values:
      layout: single
      category: maintenance
      sidebar:
        nav: "maintenance"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
  - _posts
  - /docs  # ignore Minimal Mistakes /docs
  - /test  # ignore Minimal Mistakes /test
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
